"""initial schema from §9.3.4

Revision ID: 93ea5a51b955
Revises: 
Create Date: 2026-07-02 22:41:17.540414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ea5a51b955'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campania',
    sa.Column('campania_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('producto', sa.String(length=80), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.CheckConstraint("estado IN ('planificada','activa','cerrada','cancelada')", name='ck_campania_estado'),
    sa.PrimaryKeyConstraint('campania_id')
    )
    op.create_table('cliente',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('nombre_cifrado', sa.String(), nullable=True),
    sa.Column('dni_cifrado', sa.String(), nullable=True),
    sa.Column('email_cifrado', sa.String(), nullable=True),
    sa.Column('telefono_cifrado', sa.String(), nullable=True),
    sa.Column('direccion_cifrada', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(length=50), nullable=True),
    sa.Column('marital', sa.String(length=30), nullable=True),
    sa.Column('education', sa.String(length=30), nullable=True),
    sa.Column('default_credit', sa.String(length=5), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('housing', sa.String(length=5), nullable=True),
    sa.Column('loan', sa.String(length=5), nullable=True),
    sa.Column('contact', sa.String(length=30), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=10), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('campaign', sa.Integer(), nullable=True),
    sa.Column('pdays', sa.Integer(), nullable=True),
    sa.Column('previous', sa.Integer(), nullable=True),
    sa.Column('poutcome', sa.String(length=30), nullable=True),
    sa.Column('deposit', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('cliente_id')
    )
    op.create_table('permiso',
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('recurso', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('permiso_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('rol',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rol_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.permiso_id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.rol_id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('usuario',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('nombre_completo', sa.String(length=120), nullable=False),
    sa.Column('email_corporativo', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.rol_id'], ),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('email_corporativo'),
    sa.UniqueConstraint('username')
    )
    op.create_table('asignacion',
    sa.Column('asignacion_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('campania_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('estado_contacto', sa.String(length=30), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campania_id'], ['campania.campania_id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.cliente_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('asignacion_id')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('recurso', sa.String(length=100), nullable=False),
    sa.Column('recurso_id', sa.String(length=100), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('resultado', sa.String(length=30), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('timestamp_evento', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('consentimiento',
    sa.Column('consentimiento_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('canal', sa.String(length=30), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("estado IN ('opt-in','opt-out','no informado')", name='ck_consentimiento_estado'),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.usuario_id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.cliente_id'], ),
    sa.PrimaryKeyConstraint('consentimiento_id')
    )
    op.create_table('resultado_contacto',
    sa.Column('resultado_id', sa.UUID(), nullable=False),
    sa.Column('asignacion_id', sa.UUID(), nullable=False),
    sa.Column('resultado', sa.String(length=40), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('fecha_contacto', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignacion.asignacion_id'], ),
    sa.PrimaryKeyConstraint('resultado_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_contacto')
    op.drop_table('consentimiento')
    op.drop_table('audit_log')
    op.drop_table('asignacion')
    op.drop_table('usuario')
    op.drop_table('rol_permiso')
    op.drop_table('rol')
    op.drop_table('permiso')
    op.drop_table('cliente')
    op.drop_table('campania')
    # ### end Alembic commands ###
